filter strongswan_syslog_filter {
    program("charon-nm");
};

parser strongswan_syslog_parser {
    kv-parser(
        prefix("charon-nm.")
    );
};

parser astra_strongswan_parser {
    python(
        class("syslog_ng_mod_astra.astra_syslog_ng_parser.AstraSyslogNgParser")
        options("message_type", "charon-nm"
                "message_group_key", "charon-nm.type")
    );
};

log {
    source(s_src);
    filter(strongswan_syslog_filter);
    parser(strongswan_syslog_parser);
    parser(astra_strongswan_parser);
    destination(astra_json_dst);
    flags(final);
};
