filter astra_strongswan_connection_error_filter {
    match("^strongswan_connection_error$" value("MSG.astra-charon-nm.message_id"));
};

destination astra_strongswan_connection_error_dbus_dst {
    python(
	class("syslog_ng_mod_astra.astra_syslog_ng_destination.AstraSyslogNgDestination")
	options("destination_type", "dbus"
		"message_type", "charon-nm"
		"event_user", "@all"
		"event_group", "@all"
		"event_id", "strongswanConnectionError"
		"event_title", "strongswan: ошибка подключения"
		"event_icon", ""
		"event_params", "body"
		"event_format", "{0}")
	persist-name("strongswan_connection_error")
	);
};

log {
    source(astra_events_src);
    parser(astra_events_parser);
    filter(astra_strongswan_connection_error_filter);
    destination(astra_strongswan_connection_error_dbus_dst);
};

